from backend.api.v1.schemas.auth import (
    AuthSuccessResponse,
    ErrorResponse,
    LoginRequest,
    RefreshTokenRequest,
    SignupRequest,
    UserProfileResponse,
)
from backend.api.v1.schemas.catalog import (
    AlbumResponse,
    CreateAlbumRequest,
    CreateTrackRequest,
    ListAlbumsResponse,
    ListTracksResponse,
    ModerateAlbumRequest,
    ModerateTrackRequest,
    ReplaceAlbumTracksRequest,
    ReplaceTrackAuthorsRequest,
    TrackResponse,
    UpdateAlbumRequest,
    UpdateTrackRequest,
)
from backend.api.v1.schemas.profiles import ComposerProfileResponse, MyProfileResponse, UpdateMyProfileRequest
from backend.api.v1.schemas.library import (
    AddLibraryItemRequest,
    AddPlaylistTrackRequest,
    CreatePlaylistRequest,
    LibraryItemResponse,
    ListLibraryItemsResponse,
    ListPlaylistsResponse,
    PlaylistResponse,
    ReorderPlaylistTracksRequest,
    UpdatePlaylistRequest,
)
from backend.api.v1.schemas.social import (
    CommentResponse,
    CommentWithCountersResponse,
    CreateCommentRequest,
    LikeResponse,
    ListCommentsResponse,
)
from backend.api.v1.schemas.reports import CreateReportRequest, ListReportsResponse, ReportResponse, UpdateReportStatusRequest

__all__ = [
    "SignupRequest",
    "LoginRequest",
    "RefreshTokenRequest",
    "UserProfileResponse",
    "AuthSuccessResponse",
    "ErrorResponse",
    "ComposerProfileResponse",
    "MyProfileResponse",
    "UpdateMyProfileRequest",
    "TrackResponse",
    "AlbumResponse",
    "ListTracksResponse",
    "ListAlbumsResponse",
    "CreateTrackRequest",
    "UpdateTrackRequest",
    "ReplaceTrackAuthorsRequest",
    "ModerateTrackRequest",
    "CreateAlbumRequest",
    "UpdateAlbumRequest",
    "ReplaceAlbumTracksRequest",
    "ModerateAlbumRequest",
    "PlaylistResponse",
    "ListPlaylistsResponse",
    "CreatePlaylistRequest",
    "UpdatePlaylistRequest",
    "AddPlaylistTrackRequest",
    "ReorderPlaylistTracksRequest",
    "LibraryItemResponse",
    "ListLibraryItemsResponse",
    "AddLibraryItemRequest",
    "LikeResponse",
    "CreateCommentRequest",
    "CommentResponse",
    "CommentWithCountersResponse",
    "ListCommentsResponse",
    "CreateReportRequest",
    "UpdateReportStatusRequest",
    "ReportResponse",
    "ListReportsResponse",
]
"""Pydantic schemas for v1 HTTP contracts."""
